"""Generate config/config.properties from environment variables for CI."""

from __future__ import annotations

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = PROJECT_ROOT / "config" / "config.properties"

REQUIRED = (
    "MICROSOFT_USERNAME",
    "MICROSOFT_PASSWORD",
    "SUGAR_USERNAME",
    "SUGAR_PASSWORD",
)

DEFAULTS = {
    "AUTH_BASE_URL": "https://zpa-ba.credaris.ch",
    "AUTH_HOME_PATH": "/#/home",
    "APPLICATION_URL": "https://sugar-test.intern.credaris.ch",
    "APPLICATION_HOST": "sugar-test.intern.credaris.ch",
    "APPLICATION_LOGIN_PATH": "/#/Login",
    "MICROSOFT_LOGIN_URL": "https://login.microsoftonline.com",
    "BROWSER": "chrome",
    "HEADLESS": "true",
    "REUSE_SESSION": "false",
    "CHROME_USER_DATA_DIR": ".chrome-profile/credaris-automation",
    "CHROME_PROFILE_DIRECTORY": "Default",
    "IMPLICIT_WAIT": "0",
    "EXPLICIT_WAIT": "15",
    "QUICK_POLL_TIMEOUT": "2",
    "MFA_WAIT_TIMEOUT": "600",
    "SCREENSHOT_ON_FAILURE": "true",
    "LOG_LEVEL": "INFO",
    "KEEP_BROWSER_OPEN": "false",
}


def _env(name: str, default: str = "") -> str:
    return os.getenv(name, default).strip()


def main() -> int:
    missing = [name for name in REQUIRED if not _env(name)]
    if missing:
        print("Missing required environment variables:", ", ".join(missing), file=sys.stderr)
        return 1

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = f"""# Generated by scripts/ci/generate_config_from_env.py — do not commit.

# URLs
auth.base.url={_env("AUTH_BASE_URL", DEFAULTS["AUTH_BASE_URL"])}
auth.home.path={_env("AUTH_HOME_PATH", DEFAULTS["AUTH_HOME_PATH"])}
application.url={_env("APPLICATION_URL", DEFAULTS["APPLICATION_URL"])}
application.host={_env("APPLICATION_HOST", DEFAULTS["APPLICATION_HOST"])}
application.login.path={_env("APPLICATION_LOGIN_PATH", DEFAULTS["APPLICATION_LOGIN_PATH"])}
microsoft.login.url={_env("MICROSOFT_LOGIN_URL", DEFAULTS["MICROSOFT_LOGIN_URL"])}

# Microsoft SSO credentials (ZPA / Entra ID)
microsoft.username={_env("MICROSOFT_USERNAME")}
microsoft.password={_env("MICROSOFT_PASSWORD")}

# Sugar CRM application credentials
sugar.username={_env("SUGAR_USERNAME")}
sugar.password={_env("SUGAR_PASSWORD")}

# Browser
browser={_env("BROWSER", DEFAULTS["BROWSER"])}
headless={_env("HEADLESS", DEFAULTS["HEADLESS"])}
reuse.session={_env("REUSE_SESSION", DEFAULTS["REUSE_SESSION"])}
chrome.user.data.dir={_env("CHROME_USER_DATA_DIR", DEFAULTS["CHROME_USER_DATA_DIR"])}
chrome.profile.directory={_env("CHROME_PROFILE_DIRECTORY", DEFAULTS["CHROME_PROFILE_DIRECTORY"])}

# Timeouts (seconds)
implicit.wait={_env("IMPLICIT_WAIT", DEFAULTS["IMPLICIT_WAIT"])}
explicit.wait={_env("EXPLICIT_WAIT", DEFAULTS["EXPLICIT_WAIT"])}
quick.poll.timeout={_env("QUICK_POLL_TIMEOUT", DEFAULTS["QUICK_POLL_TIMEOUT"])}
mfa.wait.timeout={_env("MFA_WAIT_TIMEOUT", DEFAULTS["MFA_WAIT_TIMEOUT"])}

# Reporting / runtime
screenshot.on.failure={_env("SCREENSHOT_ON_FAILURE", DEFAULTS["SCREENSHOT_ON_FAILURE"])}
log.level={_env("LOG_LEVEL", DEFAULTS["LOG_LEVEL"])}
keep.browser.open={_env("KEEP_BROWSER_OPEN", DEFAULTS["KEEP_BROWSER_OPEN"])}
"""
    CONFIG_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {CONFIG_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
